### ISSUE TITLE
Create an Admin for the Data Loading Management Command

### ISSUE THREAD

**Issue by ismailsunni** [konektaz/healthsites#191]
Problem
-----------
We need an front end for for the data loading management command

Proposed Solution
------------------------
We can use django admin or a fronted form that need some inputs:

1. A json concept mapping document
2. A csv delimited file with health sites data
3. The name of the origin organisation
4. A checkbox to indicate whether previous records should be replaced or update

Suggestion from @timlinux for point 4 : to use a combination of the location (with some fuzzy match) and the origin organisation to determine whether records are the same.

Sample data:
https://github.com/konektaz/healthsites/wiki/Rwanda-data

Expected Result
----------------------
The admin page allow Mark (and eventually registered users) to easily upload new data into the database.

**Comment by ismailsunni** [comment]
I made a simple mock up for the data loader UI
![Data_Loader_Form 1](https://assets.moqups.com/WzqaoLCWxO/Page_1.png)

Link to moqups: https://moqups.com/tim@kartoza.com/S6i82SXi/p:a148562f1

Which one is better? Put it as in side panel or as a modal?

**Comment by markherringer** [comment]
I think the modal works well. However, I think it's useful to be able to share the URL of the 'functionality'. So maybe the modal window could pop-up out of the dedicated /healthsites-dataloader/ page..?

**Comment by timlinux** [comment]
That looks spot on thanks @ismailsunni Lets go with the modal option for now. @markherringer I think this should be for admins only so we should not mainstream it to end users.

**Comment by markherringer** [comment]
As an administrator I need a way to find the Rwanda data easily. How do we identify the locations in the database that fall within Rwanda? Do we query the Rwanda shapefile?
